### ISSUE TITLE
from scipy.misc import imshow

### ISSUE THREAD

**Issue by clovett** [duckythescientist/SmoothLife#2]
Love your project! 

You don't need this line in the code "from scipy.misc import imshow".  Removing this helps make it work, on windows anyway, where scipy.misc.imshow is missing.  You are using matplotlib imshow anyway, so I don't think you need the scipy verison.

**Comment by abhi-jha** [comment]
Thank you. I just couldn't figure out why it didn't work even after installing all the dependencies. Commenting the line out definitely helps.

**Comment by duckythescientist** [comment]
I didn't know that that function was being deprecated. I'm actually sad about that because the matplotlib requires `plt.show()` afterward. It's no longer just a single function call.

I had it in there because running `imshow()` was super useful for debugging things and showing intermediate arrays. I'll go forward with the merge in #3 to fix the issue. Thanks!
