### ISSUE TITLE
I am getting an overflow warning.

### ISSUE THREAD

**Issue by abhi-jha** [duckythescientist/SmoothLife#4]
` RuntimeWarning: overflow encountered in exp
  logistic = 1 / (1 + np.exp(logres * (radiuses - radius)))`

**Comment by duckythescientist** [comment]
For points that are far away from the center of the `logistic2d` array, they have a large `radiuses` value which causes the exponential of that to be `+inf`. However, `1 / (1 + inf) == 0.0` which is the expected behavior and exactly what we want to happen, so everything works out just fine.

I'll go ahead and push a commit that'll suppress the overflow warnings in that section.
